libraries/imageslider/src/main/java/com/trendyol/uicomponents/imageslider/ImageSliderView.kt, libraries/imageslider/src/main/java/com/trendyol/uicomponents/imageslider/ImageSliderViewState.kt, libraries/imageslider/src/main/res/layout/view_image_slider.xml
**_isIndicatorAlwaysVisible_** field is added to **ImageSliderViewState**. This field provides to control indicator visibility. If it is true, image indicator is always visible. If it is false, then image list is controlled to decide visibility of indicator (Eg. if image size is one, indicator is visible otherwise it is visible)
=> Add indicator visibility choivr

libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/BindingAdapters.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListAdapter.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListItemViewState.kt, libraries/dialogs/src/main/res/layout/item_list.xml, libraries/dialogs/src/main/res/values/colors.xml, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt, sample/src/main/res/drawable/ic_check.xml
Implement custom selected text color and custom selected icon features.
Add selectedItemDrawable and selectedTextColor properties to SelectionDialogBuilder and pass them to the DialogListAdapter inorder to use custom colors and drawables in related views.
Test
Tested on emulator and real device with api level < 21
=> SelectedItemTextColor and SelectedItemDrawable

.idea/codeStyles/Project.xml, libraries/phonenumber/build.gradle, libraries/phonenumber/src/main/java/com/trendyol/uicomponents/phonenumber/PhoneNumberTextInputEditText.kt, sample/src/main/java/com/trendyol/uicomponents/PhoneNumberActivity.kt, sample/src/main/res/layout/activity_phone_number.xml
Add phone number masking feature to PhoneNumberTextInputEditText
=> Add phone number masking feature to PhoneNumberTextInputEditText

libraries/dialogs/README.md, libraries/dialogs/build.gradle, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt
* Implement animateCornerRadiusWhenExpand flag to disable corner radius animations.
* Update README.md and build.gradle with new version number.
Tested on physical device with Android 7.1.
=> Dialogs - Make Radius Animation Optional

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt
=> Fix content image visibility bug

libraries/suggestion-input-view/README.md, libraries/suggestion-input-view/build.gradle, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputItemViewState.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt, libraries/suggestion-input-view/src/main/res/drawable/shape_error_background_suggestion_item.xml, libraries/suggestion-input-view/src/main/res/layout/item_suggestion.xml, libraries/suggestion-input-view/src/main/res/values/attrs.xml, sample/src/main/java/com/trendyol/uicomponents/suggestioninput/SuggestionInputActivity.kt, sample/src/main/res/layout/activity_suggestion_input.xml
notify error to background change
=> Add notify error with background

libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputEditText.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputViewState.kt, libraries/suggestion-input-view/src/main/res/layout/view_suggestion_input.xml, libraries/suggestion-input-view/src/main/res/layout/view_suggestion_selectables.xml, sample/src/main/res/layout/activity_suggestion_input.xml
Fix can delete suffix or write text right of suffix
=> Create suggestion input edittext for suffix

libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Toolbar.kt, libraries/toolbar/src/main/res/values/dimens.xml
Default margin and padding values for toolbar icons and texts are updated.
Tested on Android emulator.
=> Update toolbar icon and text default margins-padding values

libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/ToolbarViewState.kt, libraries/toolbar/src/main/res/values/styles.xml
Update styles for toolbar texts
=> Update toolbar text styles

libraries/toolbar/README.md, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Toolbar.kt
Right text margins are set as 8 dp
=> Update toolbar right text default margins

libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/ToolbarViewState.kt, libraries/toolbar/src/main/res/layout/view_toolbar.xml, libraries/toolbar/src/main/res/values/styles.xml, sample/src/main/java/com/trendyol/uicomponents/ToolbarActivity.kt, sample/src/main/res/layout/activity_toolbar.xml
Setting upper right text enabled/disabled is added. Disabled upper right text appearance is added.
Tested on emulator.
=> Add right text enability options

libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/ToolbarViewState.kt
Right text in toolbar is enabled by default.
=> Make toolbar right text enabled as default option

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListAdapter.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListItemViewState.kt, libraries/dialogs/src/main/res/drawable/ic_radio_button_checked.xml, libraries/dialogs/src/main/res/layout/item_list.xml, libraries/dialogs/src/main/res/values/styles.xml, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
add left radioBottom for selection dialog
=> add radioButton to selectionDialog

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListItemViewState.kt, libraries/dialogs/src/main/res/drawable/ic_radio_button_unchecked.xml, libraries/dialogs/src/main/res/layout/item_list.xml, libraries/dialogs/src/main/res/values/styles.xml
=> selection dialog ui and checked bug

libraries/toolbar/src/main/res/layout/view_toolbar.xml
When left text is too long, left and right text collapses. This issue is fixed.
=> Fix alignment and ellipsize issue when left text is too long

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/timeline-view/README.md, libraries/timeline-view/src/main/java/com/trendyol/timelineview/SmoothScroller.kt, libraries/timeline-view/src/main/java/com/trendyol/timelineview/TimelineItemViewState.kt, libraries/timeline-view/src/main/java/com/trendyol/timelineview/TimelineView.kt, libraries/timeline-view/src/main/res/layout/item_timeline.xml, libraries/timeline-view/src/main/res/values/attrs.xml, libraries/timeline-view/src/main/res/values/dimens.xml, sample/src/main/java/com/trendyol/uicomponents/TimelineViewActivity.kt, sample/src/main/res/layout/activity_timeline_view.xml
Add lineWidth attribute
Add tooltip animation
TimelineView needs dynamic lineWidth
All TimelineView items not seen some devices. for this reason add tooltip animation
Test on emulator with 3 Timeline item and 8 Timeline item
=> lineWidth attr and tooltip animation

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/src/main/res/values/styles.xml
Fix padding and theme overlay issues
Tested on sample sample and Trenyol app
=> Bug fix/theme overlay in dialog

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListAdapter.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/list/DialogListViewModel.kt, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
=> add reselection option on selection dialog

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/TextPosition.kt, libraries/dialogs/src/main/res/layout/fragment_dialog.xml, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
=> add visibility options on info dialog

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
Click support is added for phone numbers, mails and urls
=> Add link support for dialog content

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/BindingAdapters.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/WebViewContent.kt, libraries/dialogs/src/main/res/layout/fragment_dialog.xml
- [ x] New feature (non-breaking change which adds functionality)
Web view support is added for dialogs. 
WebViewContent option is provided to show html data or web url content in web view.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
=> Web view support for dialogs

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/BindingAdapters.kt
- [ x] Bug fix (non-breaking change which fixes an issue)
dialogs web view load data method changed with loadDataWithBaseUrl
=> change dialogs web view loadData to loadDataWithBaseUrl

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/toolbar/README.md, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Extensions.kt, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Toolbar.kt, libraries/toolbar/src/main/res/layout/view_toolbar.xml
Update toolbar version to 1.2.4.
=> Fix Preview Issue on Toolbar Component

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/toolbar/README.md, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/ToolbarViewState.kt, libraries/toolbar/src/main/res/layout/view_toolbar.xml
Fix design window's preview error on Toolbar
- Update README.
- Update Toolbar component version to toolbar-2.0.4.
=> Toolbar Preview Fix

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/suggestion-input-view/README.md, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt, libraries/suggestion-input-view/src/main/res/values/attrs.xml, sample/src/main/res/layout/activity_suggestion_input.xml
=> can deselected item option

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt, sample/src/main/res/layout/activity_dialogs.xml
WebViewBuilder is added to info dialog with web view.
WebViewSettings such as javaScriptEnabled needs to be set to be able to open some urls. This is provided by WebViewBuilder.
=> Add webview builder support for dialogs with web view

libraries/image-slider/src/main/java/com/trendyol/uicomponents/imageslider/Extensions.kt, libraries/image-slider/src/main/java/com/trendyol/uicomponents/imageslider/ImageSliderView.kt, libraries/image-slider/src/main/java/com/trendyol/uicomponents/imageslider/ImageSliderViewState.kt, libraries/image-slider/src/main/java/com/trendyol/uicomponents/imageslider/ImagesPagerAdapter.kt, sample/src/main/java/com/trendyol/uicomponents/ImageSliderActivity.kt
Add the option to add radius to imageSlider
=> add corner radius in dp

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/res/layout/fragment_dialog.xml, sample/src/main/AndroidManifest.xml, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
Webview input focus problem is fixed
=> Fix webview focus problem

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/card-input-view/README.md, libraries/card-input-view/src/main/java/com/trendyol/cardinputview/CardInputView.kt, libraries/card-input-view/src/main/java/com/trendyol/cardinputview/CardInputViewState.kt, sample/src/main/java/com/trendyol/uicomponents/CardInputViewActivity.kt, sample/src/main/res/layout/activity_card_input.xml
Provides functionality to clear errors for CardInputView
To test the newly added feature, a button has been added to CardInputViewActivity which is calling clear error functionality
=> Implement clear errors functionality for CardInputView

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
* change title type with charSequence to support spannable
=> Spannable Title

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/suggestion-input-view/README.md, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt
When inputText is empty and validation false, listener should be invoke
=> Fix After Text Changed Else Case

libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
add AnimateCornerRadiusWhenExpand and titleTextColor for SelectionDialogBuilder
=> SelectionDialogAttributeUpdate

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/suggestion-input-view/README.md, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputBadge.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputItem.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputItemViewState.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt, libraries/suggestion-input-view/src/main/res/drawable/shape_background_suggestion_item_badge.xml, libraries/suggestion-input-view/src/main/res/layout/item_suggestion.xml, libraries/suggestion-input-view/src/main/res/values/attrs.xml, libraries/suggestion-input-view/src/main/res/values/colors.xml, libraries/suggestion-input-view/src/main/res/values/dimens.xml, sample/src/main/java/com/trendyol/uicomponents/SuggestionInputViewActivity.kt
Added optional badge view to suggestion input item
=> add badge to suggestion input item

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/card-input-view/README.md, libraries/card-input-view/src/main/res/drawable/shape_card_input_cvv_info_background.xml, libraries/card-input-view/src/main/res/values/colors.xml, libraries/card-input-view/src/main/res/values/dimens.xml
Fixing CardInputView CVV info field size and border color
=> CardInputView Cvv Info design fix

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/card-input-view/README.md, libraries/toolbar/README.md, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Toolbar.kt
Revert some debounced click listeners in Toolbar
Unable to get jitpack package on version 2.0.7
=> Revert some debounced click listeners to not disrupt as-is behavior

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/timeline-view/README.md, libraries/timeline-view/src/main/java/com/trendyol/timelineview/TimelineItemViewState.kt, libraries/timeline-view/src/main/java/com/trendyol/timelineview/TimelineView.kt, libraries/timeline-view/src/main/res/layout/item_timeline.xml
=> add maxLineCount parameter to TimeLineView and update README.md

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/card-input-view/README.md, libraries/card-input-view/src/main/java/com/trendyol/cardinputview/CardInputView.kt, sample/src/main/java/com/trendyol/uicomponents/CardInputViewActivity.kt
add cardNumberInputErrorListener to CardInputView
=> ANDCHECK-1930/walletCardInputViewError

libraries/dialogs/README.md
Updade README on `dialogs`.
Update dialogs README to remove enable `dataBinding` warning and fix its syntax.
README was not updated.
=> Dialogs View Binding Update

libraries/quantity-picker-view/README.md, libraries/quantity-picker-view/build.gradle.kts, libraries/quantity-picker-view/src/main/AndroidManifest.xml, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/BindingAdapters.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerView.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerViewState.kt, libraries/quantity-picker-view/src/main/res/layout/view_quantity_picker.xml, libraries/quantity-picker-view/src/main/res/layout/view_quantity_picker_vertical.xml, sample/build.gradle.kts, sample/src/main/java/com/trendyol/uicomponents/QuantityPickerViewActivity.kt
DataBinding removed from `quantityPickerView`.
- Remove dataBinding from `:quantity-picker-view` component.
- Update sample activity for `:quantity-picker-view`.
- Update README.
DataBinding removed.
Tested on emulator.
=> - Remove dataBinding from `:quantity-picker-view` component.

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/quantity-picker-view/README.md, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerView.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerViewState.kt, libraries/quantity-picker-view/src/main/res/values/attrs.xml
=> Quantity picker view/add icon and background setters

buildSrc/src/main/kotlin/ComponentVersions.kt, libraries/card-input-view/src/main/java/com/trendyol/cardinputview/CardInputView.kt
update shouldShowErrors of viewState
=> ANDCHECK-1930/walletCardInputViewErrorFix

libraries/suggestion-input-view/README.md, libraries/suggestion-input-view/build.gradle.kts, libraries/suggestion-input-view/src/main/AndroidManifest.xml, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/BindingAdapters.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/Extensions.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputItemViewState.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputView.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionInputViewState.kt, libraries/suggestion-input-view/src/main/java/com/trendyol/suggestioninputview/SuggestionItemAdapter.kt, libraries/suggestion-input-view/src/main/res/layout/item_suggestion.xml, libraries/suggestion-input-view/src/main/res/layout/view_suggestion_input.xml, libraries/suggestion-input-view/src/main/res/layout/view_suggestion_selectables.xml, libraries/suggestion-input-view/src/main/res/values/strings.xml
DataBinding migration.
- Remove dataBinding from `:suggestion-input-view` component.
- Update README.
DataBinding migration.
Tested on emulator.
=> - Remove dataBinding from `:suggestion-input-view` component.

libraries/timeline-view-compose/build.gradle.kts, libraries/timeline-view-compose/proguard-rules.pro
Disable proguard of :timeline-view-compose module
=> Disable timeLineViewCompose proguard

libraries/timeline-view-compose/README.md, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/HorizontalTimelineWithIndexTextView.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/Line.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/TimelinePoint.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/TimelineView.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/item/HorizontalTimelineImageItem.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/item/HorizontalTimelineWithIndexTextItem.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/item/VerticalTimelineItem.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/model/ConstraintSets.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/model/FakeTimelineItemProvider.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/model/PointShadowConfig.kt, libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/model/TimelineItem.kt, sample-compose/src/main/java/com/trendyol/uicomponents/samplecompose/TimelineViewItemProvider.kt, sample-compose/src/main/java/com/trendyol/uicomponents/samplecompose/TimelineViewScreen.kt
=> add shadow and index text to points and fit to screen

libraries/toolbar/README.md, libraries/toolbar/src/main/res/drawable/trendyol_uicomponents_toolbar_arrow_back.xml
=> Toolbar icon RTL support

libraries/toolbar/README.md, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Extensions.kt, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/Toolbar.kt, libraries/toolbar/src/main/java/com/trendyol/uicomponents/toolbar/ToolbarViewState.kt, libraries/toolbar/src/main/res/drawable/orange_dot.xml, libraries/toolbar/src/main/res/layout/view_toolbar.xml, libraries/toolbar/src/main/res/values/attrs.xml, sample/src/main/java/com/trendyol/uicomponents/ToolbarActivity.kt, sample/src/main/res/drawable/ic_info.xml
=> 1568 - add dot point to right drawable in toolbar

libraries/dialogs/README.md, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/Builder.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragmentArguments.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogViewState.kt, libraries/dialogs/src/main/res/layout/layout_dialog_header.xml, libraries/dialogs/src/main/res/values/dimens.xml, sample/src/main/java/com/trendyol/uicomponents/DialogsActivity.kt
add drawable and color support close button
to align with app's color schema
tested via sample app
=> Dialog close button drawable and color support

libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/DialogFragment.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/configurator/WebViewConfigurator.kt, libraries/dialogs/src/main/java/com/trendyol/uicomponents/dialogs/configurator/WebViewDownloadConfigurator.kt, sample/src/main/java/com/trendyol/uicomponents/WebViewDomAndJSEnabler.kt, sample/src/main/java/com/trendyol/uicomponents/WebViewDownloadListenerConfigurator.kt, sample/src/main/java/com/trendyol/uicomponents/WebViewJavascriptEnabler.kt
Update WebViewDownloadConfigurator and WebViewConfigurator signature
=> Update WebViewDownloadConfigurator and WebViewConfigurator signature

libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/BindingAdapters.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerTextAppearance.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerView.kt, libraries/quantity-picker-view/src/main/java/com/trendyol/uicomponents/quantitypickerview/QuantityPickerViewState.kt
development was made to solve the downloadable font problem experienced on Huawei phones
=> fix QuantityPickerView invalid font resource issue

libraries/quantity-picker-compose/src/main/java/com/trendyol/uicomponents/quantitypicker/QuantityAddIcon.kt, libraries/quantity-picker-compose/src/main/java/com/trendyol/uicomponents/quantitypicker/QuantityPicker.kt, sample-compose/src/main/java/com/trendyol/uicomponents/samplecompose/QuantityPickerScreen.kt, sample-compose/src/main/java/com/trendyol/uicomponents/samplecompose/ui/productcard/ProductCard.kt
=> Improved horizontal display of quantitypicker

libraries/quantity-picker-compose/src/main/java/com/trendyol/uicomponents/quantitypicker/QuantityAddIcon.kt, libraries/quantity-picker-compose/src/main/java/com/trendyol/uicomponents/quantitypicker/QuantityPicker.kt
=> Bugfix/quantity picker compose removed  control
